// Checkout Constants

import { ShippingAddress } from './types';

export const DEFAULT_SHIPPING_ADDRESS: ShippingAddress = {
    firstName: '',
    lastName: '',
    company: '',
    address1: '',
    address2: '',
    city: '',
    state: '',
    postalCode: '',
    country: 'US',
    phone: '',
};

export const US_STATES = [
    { code: '', name: 'Select State' },
    { code: 'AL', name: 'Alabama' },
    { code: 'AK', name: 'Alaska' },
    { code: 'AZ', name: 'Arizona' },
    { code: 'AR', name: 'Arkansas' },
    { code: 'CA', name: 'California' },
    { code: 'CO', name: 'Colorado' },
    { code: 'CT', name: 'Connecticut' },
    { code: 'DE', name: 'Delaware' },
    { code: 'FL', name: 'Florida' },
    { code: 'GA', name: 'Georgia' },
    { code: 'HI', name: 'Hawaii' },
    { code: 'ID', name: 'Idaho' },
    { code: 'IL', name: 'Illinois' },
    { code: 'IN', name: 'Indiana' },
    { code: 'IA', name: 'Iowa' },
    { code: 'KS', name: 'Kansas' },
    { code: 'KY', name: 'Kentucky' },
    { code: 'LA', name: 'Louisiana' },
    { code: 'ME', name: 'Maine' },
    { code: 'MD', name: 'Maryland' },
    { code: 'MA', name: 'Massachusetts' },
    { code: 'MI', name: 'Michigan' },
    { code: 'MN', name: 'Minnesota' },
    { code: 'MS', name: 'Mississippi' },
    { code: 'MO', name: 'Missouri' },
    { code: 'MT', name: 'Montana' },
    { code: 'NE', name: 'Nebraska' },
    { code: 'NV', name: 'Nevada' },
    { code: 'NH', name: 'New Hampshire' },
    { code: 'NJ', name: 'New Jersey' },
    { code: 'NM', name: 'New Mexico' },
    { code: 'NY', name: 'New York' },
    { code: 'NC', name: 'North Carolina' },
    { code: 'ND', name: 'North Dakota' },
    { code: 'OH', name: 'Ohio' },
    { code: 'OK', name: 'Oklahoma' },
    { code: 'OR', name: 'Oregon' },
    { code: 'PA', name: 'Pennsylvania' },
    { code: 'RI', name: 'Rhode Island' },
    { code: 'SC', name: 'South Carolina' },
    { code: 'SD', name: 'South Dakota' },
    { code: 'TN', name: 'Tennessee' },
    { code: 'TX', name: 'Texas' },
    { code: 'UT', name: 'Utah' },
    { code: 'VT', name: 'Vermont' },
    { code: 'VA', name: 'Virginia' },
    { code: 'WA', name: 'Washington' },
    { code: 'WV', name: 'West Virginia' },
    { code: 'WI', name: 'Wisconsin' },
    { code: 'WY', name: 'Wyoming' },
];

// Product pricing configuration
export const PRODUCT_PRICING: Record<string, { price: number; name: string }> = {
    'mv-hoodie': { price: 1700, name: 'MV Members Only Hoodie' },
    'mv-tee': { price: 350, name: 'MV Members Only Tee' },
    'p6': { price: 1700, name: 'Most Valuable Box Logo Hoodie' },
    'p7': { price: 1700, name: 'MV Traditional Hoodie' },
    'p1b': { price: 350, name: 'Box Logo Tee - Black' },
    'p1w': { price: 350, name: 'Box Logo Tee - White' },
    'box-logo-zipper': { price: 85, name: 'Box Logo Zipper' },
    'box-logo-beanie': { price: 85, name: 'Box Logo Beanie' },
    'raffle': { price: 100, name: 'A Valuable Shirt' },
};

// Direct purchase product IDs
export const DIRECT_PURCHASE_PRODUCT_IDS = [
    'raffle',
    'mv-hoodie',
    'mv-tee',
    'p6',
    'p7',
    'p1b',
    'p1w',
    'box-logo-zipper',
    'box-logo-beanie',
];
